# Generated by Django 5.1.4 on 2024-12-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_clientoperation_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='changed_balances',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
