# Generated by Django 5.1.4 on 2025-01-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_currency_is_deleted_customuser_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
