# Generated by Django 5.1.4 on 2024-12-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientoperation',
            name='user',
        ),
        migrations.AddField(
            model_name='clientoperation',
            name='cashier_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='clientoperation',
            name='total_in_som',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
