# Generated by Django 5.1.4 on 2025-01-02 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shift_changed_balances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
